### ISSUE TITLE
First gene not annotated if the first base of the gene is the first base of the contig 

### ISSUE THREAD

**Issue by rgladstone** [bacpop/ggCaller#19]
I ran ggcaller on 66 capsular loci extracted from references. The first base is the first base of the first gene, and the last base is the last base of the last gene.

ggcaller --refs db_fasta.txt --aligner ref --alignment pan --clean-mode sensitive --annotation sensitive --save --threads 32 --merge-paralogs --search-radius 30000 --max-orf-orf-distance 30000

For all 66 references the first gene is not annotated by ggcaller, even though it starts with the start codon 'atg' methionine. 
Prokka does annotate these first genes, and ggcaller has no issue when the last base of the stop codon is the last base of the contig. The results have one gene less than prokka + panaroo (using the same settings).

**Comment by samhorsfield96** [comment]
Hi Rebecca, could you provide an example of one of these genes that ggCaller is missing?

**Comment by rgladstone** [comment]
Thanks, here are the two annotations, one for Prokka that also contains the sequence and one from ggcaller. I've added a txt extension as github wouldn't accept .gff. It's the first gene 1-777 that isn't been captured by ggcaller.

[K1_CP000243_ggcaller.gff.txt](https://github.com/bacpop/ggCaller/files/13858419/K1_CP000243_ggcaller.gff.txt)
[K1_CP000243_prokka.gff.txt](https://github.com/bacpop/ggCaller/files/13858420/K1_CP000243_prokka.gff.txt)

**Comment by samhorsfield96** [comment]
The missing gene sequence may have been truncated or elongated incorrectly by ggCaller. Would you be able to send across the full ggCaller output folder, please? I can take a look in more detail.

**Comment by rgladstone** [comment]
Sure, I've zipped it up [here](https://drive.google.com/file/d/1CaA3-qSJRky-2aPNDWQd3dxWIDrr5LSw/view?usp=sharing)

**Comment by samhorsfield96** [comment]
Hi Rebecca, I've now implemented a change that should sort the issue in commit [bf39e1c](https://github.com/bacpop/ggCaller/pull/22/commits/bf39e1ce085c9d247c808f0166185935ea58bee9).

**Comment by samhorsfield96** [comment]
Closed as inactive.
