### ISSUE TITLE
interpret the gene_presence_absence.csv

### ISSUE THREAD

**Issue by abcdtree** [bacpop/ggCaller#26]
Hi Sam,

In the gene_presence_absence.csv table, for each genome I input, If I understand it right, there is `5_refound_-1718` or `5_0_24879` if the gene in this row presents and empty if it is not. 

I guess 5 in the front is the genome index, but what does the `refound` and `0` mean? And also what is the number at the end?

Thanks,

Josh

**Comment by samhorsfield96** [comment]
Hi Josh,
