### ISSUE TITLE
Please help with the following error 

### ISSUE THREAD

**Issue by sim3023** [bacpop/ggCaller#27]
ggcaller --refs input.txt --annotation ultrasensitive  --aligner def --alignment pan --save --out sample --threads 4
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Loading gene models...
Traversing graph to identify ORFs...
|        █         █         █         █        █| 100%
Generating clusters of high-scoring ORFs...
Scoring ORF clusters...
|██████████████████████████████████████████████████| 100%
Identifying high-scoring ORFs...
|        █         █         █         █        █| 100%
Generating initial network...
Traceback (most recent call last):
  File "/home/snp/miniconda3/envs/ggc_env/bin/ggcaller", line 33, in <module>
    sys.exit(load_entry_point('ggCaller==1.3.4', 'console_scripts', 'ggcaller')())
  File "/home/snp/miniconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/ggCaller/__main__.py", line 511, in main
    run_panaroo(pool, array_shd_tup, high_scoring_ORFs, high_scoring_ORF_edges,
  File "/home/snp/miniconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/panaroo_runner/__main__.py", line 61, in run_panaroo
    G, centroid_contexts = generate_network(shd_arr[0], overlap, high_scoring_ORFs,
  File "/home/snp/miniconda3/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/panaroo_runner/generate_network.py", line 203, in generate_network
    neighbour_cluster = seq_to_cluster[pan_neigbour_id]
KeyError: '3_0_18959'

**Comment by samhorsfield96** [comment]
Hi, would you be able to provide me with the contents of input.txt please?

**Comment by afrouin** [comment]
Hello,

I'm having the same issue than [sim3023](https://github.com/sim3023). Are they any update on that issue ? 

Best

**Comment by samhorsfield96** [comment]
Hi, could you please send me the following:
- the command used to install ggCaller
- the whole error message encountered
- the output of running `mamba list` in the `ggc_env` environment
- the command used to run ggCaller
- the contents of `input.txt` used to run ggCaller

Thank you!

**Comment by afrouin** [comment]
Hi Sam, thank you very much for your quick answer !

Unfortunately, I don't have many details on how ggcaller was installed or the ggc_env, as it was made available as a module on my institute's SLURM cluster (version 1.3.4). I can ask for more detail if necessary. 

Here is the command that i used : 
ggcaller \
  --refs scratch/genomes/input_strains_nobaddies.txt \
  --annotation ultrasensitive \
  --aligner def \
  --alignment pan \
  --save \
  --out scratch/ggc_ScreenCryo_nobaddies \
  --threads 32 \
  --quiet

Here is the whole output of my SLURM job : 

INFO:    underlay of /etc/localtime required more than 50 (75) bind mounts
Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
Traversing graph to identify ORFs...
|                                                  | 0%^H^H^H^H^H^H^H^H^H^H^H^
Generating clusters of high-scoring ORFs...
Scoring ORF clusters...
|                                                  | 0%^H^H^H^H^
Identifying high-scoring ORFs...
|                                                  | 0%^H^H^H^H^H^
Loading gene models...
Traceback (most recent call last):
  File "/opt/conda/envs/ggc_env/bin/ggcaller", line 33, in <module>
    sys.exit(load_entry_point('ggCaller==1.3.4', 'console_scripts', 'ggcaller')())
  File "/opt/conda/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/ggCaller/__main__.py", line 511, in main
    run_panaroo(pool, array_shd_tup, high_scoring_ORFs, high_scoring_ORF_edges,
  File "/opt/conda/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/panaroo_runner/__main__.py", line 61, in run_panaroo
    G, centroid_contexts = generate_network(shd_arr[0], overlap, high_scoring_ORFs,
  File "/opt/conda/envs/ggc_env/lib/python3.9/site-packages/ggCaller-1.3.4-py3.9-linux-x86_64.egg/panaroo_runner/generate_network.py", line 203, in generate_network
    neighbour_cluster = seq_to_cluster[pan_neigbour_id]
KeyError: '385_0_13571'
ERROR conda.cli.main_run:execute(124): `conda run ggcaller --refs scratch/genomes/input_strains_nobaddies.txt --annotation ultrasensitive --aligner def --alignment pan --save --out scratch/ggc_ScreenCryo_nobaddies --threads 32 --quiet` failed. (See above for error)


Also please find attached the input file.

Thank you very much for your help !

[input_strains_nobaddies.txt](https://github.com/bacpop/ggCaller/files/15093532/input_strains_nobaddies.txt)

**Comment by samhorsfield96** [comment]
I have hopefully fixed the issue in the branch `issue_27`, commit [fafcc78](https://github.com/bacpop/ggCaller/commit/fafcc781480d8ad0c1f97e8efff19814b59d61c3). If you could reinstall using this branch and then let me know whether this fixes the issue that would be fantastic, thank you.

**Comment by afrouin** [comment]
Hi Sam, sorry it took me a while to come back.

Your fix seems to do the trick and everything is working now. Thanks a lot !

Cheers
