### ISSUE TITLE
ggcaller terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by afrouin** [bacpop/ggCaller#35]
Hi Sam and all,

So i tried to run ggcaller (version 1.3.6) on my institute SLURM cluster and got the following error message:

Building coloured compacted DBG...
Generating graph stop codon index...
Mapping contigs to graph...
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 431399)
/local/scratch/tmp/tmpnm3wpbd2: line 3: 2260531 Aborted                 ggcaller --refs scratch/genomes/input_strains.txt --annotation ultrasensitive --aligner def --alignment pan --save --out scratch/ggc_ScreenCryo --threads 16 --quiet
ERROR conda.cli.main_run:execute(125): `conda run ggcaller --refs scratch/genomes/input_strains.txt --annotation ultrasensitive --aligner def --alignment pan --save --out scratch/ggc_ScreenCryo --threads 16 --quiet` failed. (See above for error)

I don't think it's a memory problem: it crashed using only 8 of the 500+G allocated ... Any idea how to fix this ?

Thanks a lot !

**Comment by samhorsfield96** [comment]
Hi, would you be able to provide the input_strains.txt file, please? Also how did you install ggCaller?

**Comment by afrouin** [comment]
Hi Sam, thank you for your answer.

Please find attached the input_strains.txt file. 

[input_strains.txt](https://github.com/user-attachments/files/16176421/input_strains.txt)

Also, i installed ggCaller using apptainer (recipe is also attached).

[ggCaller-1-3-6.txt](https://github.com/user-attachments/files/16176400/ggCaller-1-3-6.txt)

Thanks again for your help

**Comment by samhorsfield96** [comment]
Hi, is this a persistent issue? Have you tried running more than once with the same dataset and encountered the same error?

**Comment by afrouin** [comment]
Hi Sam, it worked! Thank you very much for your responsiveness and have a nice day!
